// flow-typed signature: 9dc9cabb5809a31a7c68f18fa958b4b2
// flow-typed version: <<STUB>>/bootstrap-css-only_v^3.2.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootstrap-css-only'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootstrap-css-only' {
  declare module.exports: any;
}
